management:
  endpoint:
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,hystrix.stream,metrics,mappings,loggers
  metrics:
    export:
      prometheus:
        enabled: true
